version: '3.8'

services:
  gift-indexer-front:
    image: gift-indexer-front-dev
    container_name: gift-indexer-front
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - '${DOCKER_IP}:${DOCKER_PORT}:3000'
    networks:
      - gift-indexer-front

networks:
  gift-indexer-front:
    driver: bridge
